# Generated by Django 5.0.7 on 2024-08-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalData', '0001_initial'),
        ('api', '0008_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='PersonalData.education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(blank=True, to='PersonalData.experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='PersonalData.skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(max_length=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
