# Generated by Django 5.0.7 on 2024-08-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_education_profile_experience_profile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='media/profile_images/'),
        ),
    ]
