# Generated by Django 5.0.7 on 2024-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_connection_is_accepted_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
