# Generated by Django 5.0.7 on 2024-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionnotification',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
