# Generated by Django 5.1 on 2024-09-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
