# Generated by Django 5.0.7 on 2024-09-11 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-latest_message_timestamp']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='latest_message_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
