# Generated by Django 5.0.7 on 2024-09-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='profile_images/no_photo_corp.jpg', null=True, upload_to='media/images/'),
        ),
    ]
